#!/usr/bin/env python3
"""
03_qa.py — quality assurance for the reconstructed schema timeline.

Writes data/processed/qa_report.txt. Nothing downstream should be trusted
before this report is read.

Checks performed:
  Q1  snapshot coverage: file count, usable count, date span, gaps
  Q2  monotonicity: catalog record count should grow except at known removals
  Q3  cross-source agreement over the overlap window
  Q4  change events are singular (no unexplained flip-flopping)
  Q5  schema conformance of the current catalog against the published schema,
      using the draft the schema itself declares
  Q6  schema completeness: fields present in data but absent from the schema
  Q7  named spot checks the author can reproduce by hand
"""
from __future__ import annotations

import argparse
import csv
import textwrap as _textwrap
import json
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path

import release_state

ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "processed"
RAW = ROOT / "data" / "raw"
SOURCES = ROOT / "sources"

CORE8 = ["cveID", "vendorProject", "product", "vulnerabilityName",
         "dateAdded", "shortDescription", "requiredAction", "dueDate"]

lines: list[str] = []


def out(s: str = "") -> None:
    lines.append(s)
    print(s)


def rows(name):
    with open(PROC / name, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--final", action="store_true",
                    help="assert that metadata.json says release.mode is "
                         "final; it does not set the mode")
    args = ap.parse_args()

    # Draft/final is canonical release state, not a command-line switch.
    try:
        state = release_state.load(assert_final=args.final)
    except release_state.ReleaseStateError as exc:
        print(f"[qa] {exc}", file=sys.stderr)
        return 2

    out("=" * 72)
    out("QA REPORT — KEV schema evolution")
    out("STATUS: %s. Generated by code/03_qa.py."
        % ("verified release" if state["final"] else "DRAFT"))
    out("=" * 72)
    out()

    matrix = rows("field_presence_matrix.csv")
    jrows = rows("json_field_presence.csv")
    timeline = rows("schema_timeline.csv")
    arts = rows("artifacts.csv")
    cross = rows("crosswalk.csv")
    growth = rows("catalog_growth.csv")

    # ---- Q1 coverage ------------------------------------------------------
    out("Q1. SNAPSHOT COVERAGE")
    snap_files = sorted((SOURCES / "hrbrmstr").glob("docs/*-cisa-kev.csv"))
    dates = [r["date"] for r in matrix]
    d0, d1 = date.fromisoformat(dates[0]), date.fromisoformat(dates[-1])
    span = (d1 - d0).days + 1
    out(f"  snapshot files on disk      : {len(snap_files)}")
    out(f"  usable snapshots            : {len(matrix)}")
    out(f"  unusable snapshots          : {len(snap_files) - len(matrix)}")
    out(f"  date span                   : {dates[0]} .. {dates[-1]} ({span} days)")
    out(f"  coverage                    : {100*len(matrix)/span:.2f}% of calendar days")
    gaps = [a for a in arts if a["kind"] == "coverage_gap"]
    out(f"  coverage gaps               : {len(gaps)}")
    for g in gaps:
        out(f"      {g['date']}  {g['detail']}")
    # Guard against the coverage counters drifting from the files on disk:
    # a third-source failure was once folded into this track's totals, making
    # snapshot_files exceed the number of CSV snapshots that exist.
    counted = len(matrix) + len([a for a in arts
                                 if a["kind"] == "unusable_snapshot"
                                 and a.get("source", "csv_daily") == "csv_daily"])
    out(f"  files on disk / counted     : {len(snap_files)} / {counted}")
    out(f"  PASS: counters match disk   : "
        f"{'YES' if counted == len(snap_files) else 'NO'}")
    out(f"  PASS: coverage >= 99%       : {'YES' if 100*len(matrix)/span >= 99 else 'NO'}")
    out()

    # ---- Q2 monotonicity --------------------------------------------------
    out("Q2. CATALOG SIZE MONOTONICITY")
    csvg = [r for r in growth if r["source"] == "csv_daily" and r["n_records"]]
    decs = [a for a in arts if a["kind"] == "record_count_decrease"]
    out(f"  daily observations          : {len(csvg)}")
    out(f"  first count / last count    : {csvg[0]['n_records']} ({csvg[0]['date']}) -> "
        f"{csvg[-1]['n_records']} ({csvg[-1]['date']})")
    out(f"  net growth                  : +{int(csvg[-1]['n_records']) - int(csvg[0]['n_records'])}")
    out(f"  days with a DECREASE        : {len(decs)}")
    for d in decs:
        out(f"      {d['date']}  {d['detail']}")
    out("  NOTE: decreases are expected. CISA does withdraw entries. Each one")
    out("        above is a real removal to be described, not a parsing bug.")
    out()

    # ---- Q3 cross-source agreement ----------------------------------------
    out("Q3. CROSS-SOURCE AGREEMENT (three sources)")
    out("    csv_daily        hrbrmstr daily CSV, 2021-11-12 onward")
    out("    json_official    CISA's own mirror, 2025-01-27 onward")
    out("    json_independent lucagrippa daily JSON, 2023-08-18 onward")
    # The wording below is derived from data/raw/third_source_manifest.json,
    # not typed. It previously read "its csv/ files are byte-identical to
    # hrbrmstr's (back-filled from them)" — an unconditional claim that is
    # false: only the dates before the first differing date are identical.
    # Gate Q14 now fails the build if any file states it unconditionally.
    _cx = json.loads((RAW / "third_source_manifest.json").read_text())["csv_excluded"]
    _note = (
        f"only the json/ tree of the third source is read. Its csv/ tree is "
        f"excluded in full, for two distinct reasons. For all "
        f"{_cx['dates_before_that_all_identical']} shared dates before "
        f"{_cx['all_identical_before']} those files are byte-identical to "
        f"hrbrmstr's and appear to be back-filled copies. The "
        f"{_cx['differing_from_primary']} later shared-date files do differ, "
        f"and are excluded because this repository's independently collected "
        f"JSON already represents that collector — counting both formats "
        f"would count one collector twice. Per-date hashes: "
        f"data/raw/{_cx['per_date_hashes_file']}.")
    for i, ln in enumerate(_textwrap.wrap(_note, 64)):
        out(("    NOTE: " if i == 0 else "          ") + ln)
    n = len(cross)
    ok = sum(int(r["agree"]) for r in cross)
    three = sum(1 for r in cross if r["n_sources"] == "3")
    out(f"  days with >=2 sources       : {n}")
    out(f"  days with 3 sources         : {three}")
    out(f"  days all sources agree      : {ok}")
    out(f"  agreement rate              : {100*ok/n:.2f}%")
    dis = [r for r in cross if not int(r["agree"])]
    out(f"  disagreements               : {len(dis)}")
    for r in dis[:20]:
        out(f"      {r['date']}  {r['disagreement']}")
    if dis:
        out("  EXPLANATION: the sole disagreement is a fetch-timing artifact, not")
        out("        a contradiction. On 2026-09-01 the independent archiver")
        out("        captured catalogVersion 2026.08.31 (the previous day's")
        out("        catalog) because it fetched before CISA published. Keyed on")
        out("        catalogVersion rather than capture date, all three sources")
        out("        agree: forensicTriage is absent in v2026.08.31 and present")
        out("        in v2026.09.01. See Q3b.")
    out(f"  PASS: <=1 disagreement, explained : "
        f"{'YES' if len(dis) <= 1 else 'NO'}")
    out()

    # ---- Q3b catalogVersion reconciliation --------------------------------
    out("Q3b. CATALOG VERSION RECONCILIATION (capture date vs catalog version)")
    import glob as _glob
    ind = {}
    for p_ in sorted(_glob.glob(str(SOURCES / "lucagrippa" / "json" / "*.json"))):
        day = Path(p_).name[:10]
        if day < "2026-08-25":
            continue
        try:
            doc = json.loads(Path(p_).read_text(encoding="utf-8", errors="replace"))
        except json.JSONDecodeError:
            continue
        if not doc.get("vulnerabilities"):
            continue
        ind[day] = (doc.get("catalogVersion"),
                    any("forensicTriage" in v for v in doc["vulnerabilities"]))
    off = {r["date"]: (r["catalogVersion"], r.get("forensicTriage") == "1")
           for r in jrows}
    out("  capture      independent            official")
    for day in sorted(set(ind) | set(off)):
        if day < "2026-08-29":
            continue
        i, o = ind.get(day), off.get(day)
        fi = f"v{i[0]} ft={'Y' if i[1] else 'N'}" if i else "(none)"
        fo = f"v{o[0]} ft={'Y' if o[1] else 'N'}" if o else "(none)"
        out(f"  {day}   {fi:22} {fo}")
    out("  CONCLUSION: forensicTriage enters at catalogVersion 2026.09.01 in")
    out("        every source that holds that version. Capture date is not")
    out("        catalog version; the timeline is reported on capture date and")
    out("        this is the one place the distinction is material.")
    out()

    # ---- Q4 change events singular ----------------------------------------
    out("Q4. CHANGE EVENTS")
    csv_ev = [r for r in timeline if r["track"] == "csv_daily" and r["event"] != "baseline"]
    json_ev = [r for r in timeline if r["track"] == "json_official" and r["event"] != "baseline"]
    out(f"  csv track events            : {len(csv_ev)}")
    for r in csv_ev:
        out(f"      {r['date']}  {r['event']:<14} {r['field']}")
    out(f"  json track events           : {len(json_ev)}")
    for r in json_ev:
        out(f"      {r['date']}  {r['event']:<14} {r['field']}")
    per_field = Counter(r["field"] for r in csv_ev)
    multi = {f: c for f, c in per_field.items() if c > 1}
    out(f"  fields with >1 event        : {multi if multi else 'none'}")
    out("  NOTE: 'notes' has two events (one removal, one restoration). That is")
    out("        a genuine round trip, not flip-flopping.")
    out(f"  PASS: no field changes >2x  : {'YES' if all(c <= 2 for c in per_field.values()) else 'NO'}")
    out()

    # ---- Q5 schema conformance -------------------------------------------
    out("Q5. SCHEMA CONFORMANCE OF THE CURRENT CATALOG")
    schema = json.loads((RAW / "known_exploited_vulnerabilities_schema.json").read_text())
    data = json.loads((SOURCES / "cisagov" / "known_exploited_vulnerabilities.json").read_text())
    declared = schema.get("$schema", "")
    out(f"  schema declares draft       : {declared}")
    try:
        from jsonschema import Draft7Validator, Draft202012Validator
        V = Draft7Validator if "draft-07" in declared else Draft202012Validator
        errs = list(V(schema).iter_errors(data))
        out(f"  validator used              : {V.__name__}")
        out(f"  validation errors           : {len(errs)}")
        for e in errs[:5]:
            out(f"      {list(e.path)[:4]}: {e.message[:120]}")
        out(f"  PASS: catalog validates     : {'YES' if not errs else 'NO'}")
    except ImportError:
        out("  jsonschema not installed; conformance check SKIPPED")
    out()

    # ---- Q6 schema completeness ------------------------------------------
    out("Q6. SCHEMA COMPLETENESS (the central finding)")
    vd = schema.get("$defs", {}).get("vulnerability", {})
    described = set(vd.get("properties", {}).keys())
    observed = set()
    for v in data.get("vulnerabilities", []):
        observed.update(v.keys())
    undescribed = sorted(observed - described)
    unobserved = sorted(described - observed)
    addl = vd.get("additionalProperties", None)
    out(f"  fields described by schema  : {len(described)}")
    out(f"  fields present in data      : {len(observed)}")
    out(f"  in data, NOT in schema      : {undescribed if undescribed else 'none'}")
    out(f"  in schema, NOT in data      : {unobserved if unobserved else 'none'}")
    out(f"  additionalProperties setting: {addl if addl is not None else 'UNSET (permissive)'}")
    out("  CONSEQUENCE: because additionalProperties is unset, JSON Schema")
    out("        accepts undescribed fields silently. The catalog therefore")
    out("        validates (Q5) while the schema does not describe all of it.")
    out("        A consumer generating types from the schema drops the field")
    out("        with no error. This is a documentation gap, NOT a validation")
    out("        failure, and the report must say so in those terms.")
    # schema file history
    log = subprocess.run(
        ["git", "log", "--format=%H|%cI", "--", "known_exploited_vulnerabilities_schema.json"],
        cwd=SOURCES / "cisagov", capture_output=True, text=True, check=True).stdout.strip().splitlines()
    out(f"  schema file commit count    : {len(log)}")
    if log:
        first = log[-1].split("|")[1][:10]
        last = log[0].split("|")[1][:10]
        out(f"  schema first committed      : {first}")
        out(f"  schema last modified        : {last}")
        asof = dates[-1]
        stale = (date.fromisoformat(asof) - date.fromisoformat(last)).days
        out(f"  days unmodified as of {asof}: {stale}")
    out()

    # ---- Q7 spot checks ---------------------------------------------------
    out("Q7. NAMED SPOT CHECKS (reproduce these by hand before release)")
    checks = [
        ("2021-11-12", "first snapshot; header should be human-readable labels "
                       "beginning 'CVE,Vendor/Project'"),
        ("2021-12-01", "camelCase rename; header should begin 'cveID,vendorProject'"),
        ("2023-10-12", "knownRansomwareCampaignUse first present"),
        ("2024-06-26", "cwes first present"),
        ("2026-08-31", "forensicTriage ABSENT (the day before)"),
        ("2026-09-01", "forensicTriage PRESENT (the day of)"),
    ]
    bydate = {r["date"]: r for r in matrix}
    for d, what in checks:
        r = bydate.get(d)
        if not r:
            out(f"  {d}  MISSING SNAPSHOT — investigate")
            continue
        present = [k for k, v in r.items()
                   if k not in ("date", "n_records", "header_style") and v == "1"]
        out(f"  {d}  n={r['n_records']:>5}  style={r['header_style']}")
        out(f"              expect: {what}")
        out(f"              fields: {','.join(present)}")
    out()

    # ---- Q8 metadata integrity -------------------------------------------
    out("Q8. METADATA INTEGRITY")
    cff_path = ROOT / "CITATION.cff"
    try:
        import yaml
        cff = yaml.safe_load(cff_path.read_text())
        authors_json = json.loads((ROOT / "AUTHORS.json").read_text())["authors"]
        a0, c0 = authors_json[0], cff["authors"][0]
        checks = [
            ("CITATION.cff parses as YAML", True),
            ("title present and non-empty", bool(cff.get("title", "").strip())),
            ("family-names matches AUTHORS.json", c0["family-names"] == a0["family"]),
            ("given-names matches AUTHORS.json", c0["given-names"] == a0["given"]),
            ("affiliation matches AUTHORS.json", c0["affiliation"] == a0["affiliation"]),
            ("orcid matches AUTHORS.json",
             c0["orcid"].endswith(a0["orcid"])),
            ("licence is CC-BY-4.0", cff.get("license") == "CC-BY-4.0"),
            ("abstract present", bool(cff.get("abstract", "").strip())),
        ]
        for label, ok in checks:
            out(f"  {'PASS' if ok else 'FAIL'}  {label}")
        out(f"  PASS: metadata coherent     : "
            f"{'YES' if all(ok for _, ok in checks) else 'NO'}")
    except Exception as exc:
        out(f"  FAIL  CITATION.cff could not be validated: {exc}")
        out("  PASS: metadata coherent     : NO")
    out()

    # ---- Q9 title integrity (defect A2) -----------------------------------
    out("Q9. TITLE INTEGRITY")
    import re as _re
    META = json.loads((ROOT / "metadata.json").read_text())
    canon = META["title"]

    def norm(x):
        return _re.sub(r"[^a-z0-9]", "", x.lower())

    def strip_canon(text):
        """Remove canonical-title occurrences before hunting for old ones.

        A superseded title can be a strict PREFIX of the canonical one -- the
        pre-V5 title is exactly the current title without its subtitle -- so a
        naive substring search reports it as present in every correct document.
        """
        return norm(text).replace(norm(canon), "|")

    title_checks = []
    # report markdown: canonical H1, exactly once
    rep = (ROOT / "report" / "kev_schema_evolution.md").read_text()
    h1 = [ln for ln in rep.splitlines() if ln.startswith("# ")]
    title_checks.append(("report H1 is the canonical title",
                         len(h1) == 1 and h1[0][2:].strip() == canon))
    # README H1
    rdm = (ROOT / "README.md").read_text()
    r1 = [ln for ln in rdm.splitlines() if ln.startswith("# ")]
    title_checks.append(("README H1 is the canonical title",
                         len(r1) >= 1 and r1[0][2:].strip() == canon))
    # CITATION.cff
    try:
        import yaml as _yaml
        cffd = _yaml.safe_load((ROOT / "CITATION.cff").read_text())
        title_checks.append(("CITATION.cff title matches",
                             cffd.get("title") == canon))
    except Exception:
        title_checks.append(("CITATION.cff title matches", False))
    # rendered PDF, page 1
    pdf = ROOT / "report" / "kev_schema_evolution.pdf"
    if pdf.exists():
        try:
            txt = subprocess.run(["pdftotext", "-f", "1", "-l", "1", str(pdf), "-"],
                                 capture_output=True, text=True, check=True).stdout
            n_canon = norm(txt).count(norm(canon))
            title_checks.append(("canonical title appears exactly once on PDF page 1",
                                 n_canon == 1))
            residue = strip_canon(txt)
            stale = [t for t in META.get("superseded_titles", [])
                     if norm(t) in residue]
            title_checks.append(("no superseded title on PDF page 1", not stale))
            if stale:
                for t in stale:
                    out(f"      STALE TITLE FOUND: {t}")
        except Exception as exc:
            title_checks.append((f"PDF page 1 readable ({exc})", False))
    else:
        title_checks.append(("PDF present for title check", False))
    # no superseded title anywhere in the published documents
    for name, path in (("report", ROOT / "report" / "kev_schema_evolution.md"),
                       ("README", ROOT / "README.md"),
                       ("CITATION.cff", ROOT / "CITATION.cff")):
        residue = strip_canon(path.read_text())
        bad = [t for t in META.get("superseded_titles", []) if norm(t) in residue]
        title_checks.append((f"no superseded title in {name}", not bad))

    for label, ok in title_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: title consistent      : "
        f"{'YES' if all(ok for _, ok in title_checks) else 'NO'}")
    out()

    # ---- Q10 release-notes / publish-guide consistency (defect A4) ---------
    out("Q10. RELEASE NOTES AND PUBLISH GUIDE")
    S = json.loads((ROOT / "report" / "stats.json").read_text())
    rn_path = ROOT / "docs" / "RELEASE_NOTES.md"
    guide = (ROOT / "docs" / "PUBLISH_GUIDE.md").read_text()
    rn_checks = [("docs/RELEASE_NOTES.md exists", rn_path.exists())]
    if rn_path.exists():
        rn = rn_path.read_text()
        must = {
            "multi-source days": f"{S['crossvalidation']['multi_source_days']:,}",
            "agreement": f"{S['crossvalidation']['agreement_pct']}%",
            "total events": str(S["events"]["total_schema_evolution_events"]),
            "transitions": str(S["events"]["field_presence_transitions"]),
            "naming events": str(S["events"]["naming_or_canonicalization_events"]),
            "derived-data licence": META["licenses"]["derived_data"],
            "canonical title": canon,
            "data cutoff": S["data_cutoff"],
        }
        for label, val in must.items():
            rn_checks.append((f"release notes carry current {label} ({val})",
                              val in rn))
        # regenerating must be a no-op: proves the file is not hand-edited
        before = rn
        subprocess.run([sys.executable, str(ROOT / "code" / "07_release_notes.py")],
                       capture_output=True, check=False)
        rn_checks.append(("release notes are generated, not hand-edited",
                          rn_path.read_text() == before))
    # the guide must not restate figures
    stale_markers = ["229 overlapping", "100% agreement", "CC0-1.0",
                     "Five schema change events", "five change events"]
    found = [m for m in stale_markers if m in guide]
    rn_checks.append(("publish guide restates no superseded figures", not found))
    if found:
        for m in found:
            out(f"      STALE IN PUBLISH GUIDE: {m!r}")
    rn_checks.append(("publish guide points at the generated notes",
                      "RELEASE_NOTES.md" in guide))
    for label, ok in rn_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: release metadata sound: "
        f"{'YES' if all(ok for _, ok in rn_checks) else 'NO'}")
    out()

    # ---- Q11 generated documents are not hand-edited (defect A3) ----------
    out("Q11. GENERATED DOCUMENTS")
    gen_checks = []
    for tmpl, dst in (("templates/README.md.template", "README.md"),
                      ("templates/LIMITATIONS.md.template", "docs/LIMITATIONS.md")):
        tpath, dpath = ROOT / tmpl, ROOT / dst
        gen_checks.append((f"{tmpl} exists", tpath.exists()))
        if not (tpath.exists() and dpath.exists()):
            gen_checks.append((f"{dst} rendered", False))
            continue
        before = dpath.read_text()
        subprocess.run([sys.executable, str(ROOT / "code" / "08_render_docs.py")],
                       capture_output=True, check=False)
        gen_checks.append((f"{dst} matches its template (not hand-edited)",
                           dpath.read_text() == before))
    # no count typed into a generated document that the template did not supply
    ev_ = json.loads((ROOT / "report" / "stats.json").read_text())["events"]
    rdm_ = (ROOT / "README.md").read_text()
    lim_ = (ROOT / "docs" / "LIMITATIONS.md").read_text()
    tot = str(ev_["total_schema_evolution_events"])
    tr = str(ev_["field_presence_transitions"])
    for name, body in (("README", rdm_), ("LIMITATIONS", lim_)):
        gen_checks.append((f"{name} states the total ({tot}) and transitions ({tr})",
                           tot in body and tr in body))
        # the old conflation: both "six change events" and "five change events"
        bad = ("six change events" in body.lower()
               and "five change events" in body.lower())
        gen_checks.append((f"{name} does not conflate the two counts", not bad))
    for label, ok in gen_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: docs generated cleanly: "
        f"{'YES' if all(ok for _, ok in gen_checks) else 'NO'}")
    out()

    # ---- Q12 link hygiene (defect C1) -------------------------------------
    out("Q12. LINK HYGIENE")
    import re as _re2
    link_checks = []
    # Any github blob/raw URL whose ref is not a 40-hex commit is mutable and
    # will eventually show different bytes than this build read. The author
    # found one built on a branch that does not exist at all.
    MUTABLE = _re2.compile(
        r"https://(?:github\.com|raw\.githubusercontent\.com)/[\w.-]+/[\w.-]+/"
        r"(?:blob/|raw/)?(?!(?:[0-9a-f]{40})[/\b])([\w.-]+)/")
    # Documents a reader follows. Source files are excluded: they contain URL
    # TEMPLATES with {placeholders}, not links, and scanning them reports the
    # template braces as branch names.
    durable = ["report/kev_schema_evolution.md", "README.md",
               "docs/LIMITATIONS.md", "docs/PUBLISH_GUIDE.md",
               "docs/SNAPSHOT_LINKS.md", "docs/RELEASE_NOTES.md",
               "docs/ENVIRONMENT.md", "docs/CODEBOOK.md"]
    for rel in durable:
        f = ROOT / rel
        if not f.exists():
            continue
        body = f.read_text()
        hits = []
        for m in _re2.finditer(r"https://(?:github\.com|raw\.githubusercontent\.com)/\S+", body):
            url = m.group(0).rstrip(").,`\"'")
            parts = url.split("/")
            # .../owner/repo[/blob|/raw]/<ref>/...  -> find the ref segment
            ref = None
            for i, seg in enumerate(parts):
                if seg in ("blob", "raw") and i + 1 < len(parts):
                    ref = parts[i + 1]
                    break
            else:
                # raw.githubusercontent.com/<owner>/<repo>/<ref>/<path...>
                # parts: ['https:', '', host, owner, repo, ref, ...]
                if "raw.githubusercontent.com" in url and len(parts) > 5:
                    ref = parts[5]
            if "{" in url:          # a template, not a link
                continue
            if ref and not _re2.fullmatch(r"[0-9a-f]{40}", ref) and ref != "YYYY-MM-DD":
                hits.append((ref, url[:88]))
        link_checks.append((f"{rel}: no mutable-ref GitHub URL", not hits))
        for ref, url in hits[:3]:
            out(f"      MUTABLE REF {ref!r}: {url}")
    # the generated link file must match regeneration
    sl = ROOT / "docs" / "SNAPSHOT_LINKS.md"
    link_checks.append(("docs/SNAPSHOT_LINKS.md exists", sl.exists()))
    if sl.exists():
        before = sl.read_text()
        subprocess.run([sys.executable, str(ROOT / "code" / "09_snapshot_links.py")],
                       capture_output=True, check=False)
        link_checks.append(("snapshot links are generated, not hand-edited",
                            sl.read_text() == before))
        pin = json.loads((ROOT / "data" / "raw" / "source_pins.json")
                         .read_text())["hrbrmstr"]["commit"]
        link_checks.append(("snapshot links use the pinned hrbrmstr commit",
                            pin in sl.read_text()))
        link_checks.append(("snapshot links contain no `main` branch path",
                            "/blob/main/" not in sl.read_text()))
    for label, ok in link_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: links durable         : "
        f"{'YES' if all(ok for _, ok in link_checks) else 'NO'}")
    out()

    # ---- Q13 release-state integrity (author ruling: Option B) ------------
    # Everything that must be correct at release — banner, DOI, release date,
    # version — is generated from metadata.json's release block. This gate
    # checks that the generated artifacts still agree with it, and that a
    # draft build contains no DOI of any kind.
    out("Q13. RELEASE-STATE INTEGRITY")
    rel_checks = []
    readme_txt = (ROOT / "README.md").read_text()
    cff_txt = (ROOT / "CITATION.cff").read_text()
    report_txt = (ROOT / "report" / "kev_schema_evolution.md").read_text() \
        if (ROOT / "report" / "kev_schema_evolution.md").exists() else ""
    issue_p = ROOT / "docs" / "CISA_ISSUE.md"
    stats_j = json.loads((ROOT / "report" / "stats.json").read_text())

    out(f"  mode                       : {state['mode']}")
    out(f"  version                    : {state['version_string']}")
    out(f"  doi                        : {state['doi'] or '(none — draft)'}")
    out(f"  release date               : "
        f"{state['release_date'] or '(none — draft)'}")

    expected_banner = release_state.readme_banner(state, stats_j).rstrip("\n")
    rel_checks.append(("README banner matches the generated release state",
                       expected_banner in readme_txt))
    rel_checks.append(("README carries exactly one STATUS line",
                       readme_txt.count("**STATUS:") == 1))
    rel_checks.append(("CITATION.cff version matches the release state",
                       f'version: "{state["version"]}"' in cff_txt))
    if report_txt:
        # Compared without the generation timestamp: this gate also runs
        # mid-pipeline, before 05_document.py has rebuilt the report against
        # the current stats.json, and a timestamp difference there is expected
        # rather than a defect. Version, DOI and dates are all still checked.
        exp_id = release_state.report_identity_line(
            state, stats_j).split(" · generated")[0]
        rel_checks.append(("report identity line matches the release state",
                           exp_id in report_txt))
    # The author's own verification dates are historical facts, not build
    # facts. Item 10 of docs/LIMITATIONS.md used to take this from
    # stats.access_date, so a rebuild on a later day rewrote the date on which
    # the author was said to have checked the live CISA URLs. It is now a
    # recorded constant, and this gate holds the rendered document to it.
    meta_j = json.loads((ROOT / "metadata.json").read_text())
    av = meta_j.get("author_verification", {})
    bdate = av.get("section_b_live_check_date")
    lim_p = ROOT / "docs" / "LIMITATIONS.md"
    lim_txt = lim_p.read_text() if lim_p.exists() else ""
    rel_checks.append(("author Section B check date is recorded",
                       bool(bdate) and bool(_re2.fullmatch(r"\d{4}-\d{2}-\d{2}",
                                                          str(bdate)))))
    if bdate and lim_txt:
        sent = [ln for ln in lim_txt.splitlines()
                if "the author fetched the" in ln]
        rel_checks.append(
            ("LIMITATIONS item 10 cites the recorded author-check date, "
             "not the build's access date",
             bool(sent) and bdate in " ".join(sent)))
    rel_checks.append(("docs/CISA_ISSUE.md exists", issue_p.exists()))
    if issue_p.exists():
        before = issue_p.read_text()
        subprocess.run([sys.executable, str(ROOT / "code" / "10_cisa_issue.py")],
                       capture_output=True, check=False)
        rel_checks.append(("CISA issue text is generated, not hand-edited",
                           issue_p.read_text() == before))

    doi_re = _re2.compile(r"10\.\d{4,9}/[-._;()/:A-Za-z0-9]+")

    def dois_in(text):
        # Normalised: the DOI suffix grammar allows brackets and dots, so a
        # bare match swallows markdown punctuation and a badge URL's `.svg`.
        found = set()
        for m in doi_re.findall(text):
            d = m.rstrip(".,;:)]}\"'")
            found.add(d[:-4] if d.endswith(".svg") else d)
        return found
    scanned = {"README.md": readme_txt, "CITATION.cff": cff_txt,
               "report/kev_schema_evolution.md": report_txt,
               "docs/CISA_ISSUE.md": issue_p.read_text() if issue_p.exists() else "",
               "docs/RELEASE_NOTES.md":
                   (ROOT / "docs" / "RELEASE_NOTES.md").read_text()
                   if (ROOT / "docs" / "RELEASE_NOTES.md").exists() else ""}
    if state["final"]:
        for name in ("README.md", "CITATION.cff",
                     "report/kev_schema_evolution.md", "docs/CISA_ISSUE.md"):
            rel_checks.append((f"{name} carries the release DOI",
                               state["doi"] in scanned[name]))
        rel_checks.append(("CITATION.cff carries the release date",
                           f'date-released: "{state["release_date"]}"'
                           in cff_txt))
        stray = sorted({d for txt in scanned.values() for d in dois_in(txt)
                        if d != state["doi"]})
        rel_checks.append(("no DOI other than the release DOI appears",
                           not stray))
        for d in stray[:3]:
            out(f"      STRAY DOI {d}")
    else:
        found = {n: sorted(dois_in(txt))
                 for n, txt in scanned.items() if dois_in(txt)}
        rel_checks.append(("draft build contains no DOI, real or placeholder",
                           not found))
        for n, ds in list(found.items())[:3]:
            out(f"      DOI IN DRAFT {n}: {ds}")
        rel_checks.append(("draft CITATION.cff has no date-released",
                           "date-released:" not in cff_txt))
    for label, ok in rel_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: release state coherent: "
        f"{'YES' if all(ok for _, ok in rel_checks) else 'NO'}")
    out()

    # ---- Q14 CSV-exclusion language integrity ------------------------------
    # The third source's csv/ tree is excluded for two different reasons, and
    # the difference matters: the shared dates before 2023-09-12 are
    # byte-identical copies, while the 163 later ones genuinely differ and are
    # excluded only because that collector is already represented by its JSON.
    # Every number here comes from data/raw/third_source_manifest.json.
    # An unconditional "its CSVs are byte-identical" claim survived in the
    # generated QA report, in the pin description written into
    # data/raw/source_pins.json, and in a source comment, contradicting the
    # manifest, the report, the README, LIMITATIONS and author ruling V3.
    #
    # This gate ties the language to the derived statistics. Every claim that
    # the third source's CSVs are byte-identical must (a) be scoped — the
    # sentence has to say the identity holds *before* some boundary — and
    # (b) carry a derived reference: one of the manifest's own numbers, one of
    # its field names, or a pointer to the manifest file.
    out("Q14. CSV-EXCLUSION LANGUAGE INTEGRITY")
    cxs = json.loads((RAW / "third_source_manifest.json").read_text())["csv_excluded"]
    boundary = str(cxs["all_identical_before"])
    n_identical = str(cxs["dates_before_that_all_identical"])
    n_differ = str(cxs["differing_from_primary"])
    DERIVED = (boundary, n_identical, n_differ, "all_identical_before",
               "dates_before_that_all_identical", "differing_from_primary",
               "third_source_manifest.json")
    SCOPE = ("before", "prior to", "until", "earlier than", boundary,
             n_identical)
    claim_re = _re2.compile(r"byte[- ]identical", _re2.I)
    # "1590/1753 CSVs byte-identical" and its f-string form are partial claims
    # by construction, so a ratio counts as scoping.
    ratio_re = _re2.compile(r"(\d[\d,]*|\{[a-z_]+\}|len\()\s*/\s*"
                            r"(\d|\{|len\()")
    # A sentence that quotes the old, wrong wording in order to record that it
    # was corrected is not itself a claim. The marker has to be written
    # deliberately, so it cannot be reached by accident.
    EXEMPT = "superseded wording"
    exts = {".py", ".md", ".txt", ".json", ".template", ".sh", ".cff", ".yml"}
    skip_dirs = {"sources", "venv", "__pycache__", ".git"}
    lang_problems = []
    scanned_n = claims_n = 0
    # Claims are counted once per distinct sentence per file. Without this the
    # counter is not reproducible: data/raw/PROVENANCE.txt is an append-only
    # ledger, so every pipeline run adds another copy of the same sentence and
    # the count rises with the number of runs. Clean room D caught exactly that
    # — 24 in the working tree against 25 in the room — which is the kind of
    # drift the clean-room comparison exists to surface.
    seen_claims: set[tuple[str, str]] = set()
    ts_re = _re2.compile(r"20\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ")
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in exts:
            continue
        rel = path.relative_to(ROOT)
        if any(part in skip_dirs for part in rel.parts):
            continue
        if rel.parts[:2] == ("verification", "logs"):
            continue          # historical run logs: a record, not a claim
        if rel.as_posix() == "code/tests/negative_release_tests.py":
            # The negative-test fixtures are wrong wording on purpose: the
            # suite writes them into throwaway copies and asserts that this
            # gate rejects each one. Scanning the fixtures themselves would
            # make the test suite permanently fail the gate it tests.
            continue
        if rel.as_posix() == "data/processed/qa_report.txt":
            # This gate's own output. It quotes any offending sentence it
            # finds, so scanning it would make one real defect reappear as a
            # fresh defect on every subsequent run. The report's Q3 note is
            # checked directly below instead, against the same statistics.
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if rel.as_posix() == "data/raw/PROVENANCE.txt":
            # Append-only ledger. Lines written before the correction marker
            # record what was recorded at the time and are not rewritten; only
            # what has been appended since is held to the current wording.
            marker = "# CORRECTION"
            if marker in text:
                text = text.split(marker, 1)[1]
            else:
                continue
        scanned_n += 1
        for m in claim_re.finditer(text):
            # The claim's sentence: back to the previous sentence end or blank
            # line, forward to the next sentence end.
            left = max(text.rfind(". ", 0, m.start()),
                       text.rfind("\n\n", 0, m.start()))
            right = text.find(".", m.end())
            sentence = text[(left + 1 if left > 0 else 0):
                            (right + 1 if right > 0 else len(text))]
            if "csv" not in sentence.lower():
                continue      # a claim about something else (figures, files)
            if EXEMPT in sentence.lower():
                continue      # quotes the old wording to record the fix
            key = (rel.as_posix(),
                   " ".join(ts_re.sub("<ts>", sentence).split()))
            if key in seen_claims:
                continue      # same sentence, same verdict, already counted
            seen_claims.add(key)
            claims_n += 1
            line_no = text.count("\n", 0, m.start()) + 1
            window = text[max(0, m.start() - 600):m.end() + 600]
            scoped = (any(s in sentence.lower() for s in
                          (x.lower() for x in SCOPE))
                      or bool(ratio_re.search(sentence)))
            derived = any(d in window for d in DERIVED)
            # Drift check: any calendar date inside the claim sentence must
            # be the boundary the manifest derived. A sentence that keeps the
            # right shape but names the wrong date is the failure mode this
            # gate exists to prevent.
            bad_dates = [d for d in _re2.findall(r"\d{4}-\d{2}-\d{2}",
                                                 sentence) if d != boundary]
            if not scoped or not derived or bad_dates:
                why = ("unscoped claim" if not scoped else
                       "no derived reference" if not derived else
                       f"date disagrees with the manifest: {bad_dates[0]} "
                       f"(derived boundary {boundary})")
                lang_problems.append((f"{rel}:{line_no}", why,
                                      " ".join(sentence.split())[:150]))
    out(f"  files scanned               : {scanned_n}")
    out(f"  CSV byte-identity claims    : {claims_n}")
    out(f"  derived boundary            : {boundary} "
        f"({n_identical} identical, {n_differ} differing)")
    for where, why, snippet in lang_problems[:10]:
        out(f"      {why}: {where}")
        out(f"        {snippet}")
    lang_checks = [
        ("every CSV byte-identity claim is scoped and derived",
         not lang_problems),
        ("at least one such claim exists to check", claims_n > 0),
        ("the QA report's Q3 note is scoped to the derived boundary",
         all(v in "\n".join(lines[:80])
             for v in (boundary, n_identical, n_differ))),
        # The superseded wording is spelled in two pieces so that this
        # detector does not itself read as a claim to the scan above.
        ("the QA report's Q3 note makes no unconditional identity claim",
         ("files are byte-" + "identical to hrbrmstr's")
         not in "\n".join(lines)),
    ]
    for label, ok in lang_checks:
        out(f"  {'PASS' if ok else 'FAIL'}  {label}")
    out(f"  PASS: CSV language sound    : "
        f"{'YES' if all(ok for _, ok in lang_checks) else 'NO'}")
    out()

    out("=" * 72)
    out("END QA REPORT")
    out("=" * 72)

    (PROC / "qa_report.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
