#!/usr/bin/env python3
"""
compare_cleanroom.py — compare a clean-room build against the working tree.

Every file must either be byte-identical or have a stated, checked reason for
differing. A file that differs for a reason this script cannot account for is
printed as INVESTIGATE rather than quietly folded into a "volatile" list.

The earlier clean-room comparisons were produced ad hoc. This is the same
comparison as a committed script, so the evidence can be regenerated by someone
who was not present when it ran.

Usage:
    python code/tests/compare_cleanroom.py /path/to/cleanroom [> log]
"""
from __future__ import annotations

import datetime
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SKIP = {"sources", "venv", "__pycache__", ".git"}

# Lines whose difference is explained by an embedded build timestamp.
TS = re.compile(rb"(20\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ"
                rb"|20\d\d-\d\d-\d\d \d\d:\d\d:\d\d"
                rb"|/D:20\d{12}|generated_utc|CreationDate|ModDate)")


def files(base: Path) -> dict[str, str]:
    out = {}
    for p in base.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(base)
        if any(part in SKIP for part in rel.parts):
            continue
        if rel.parts[:2] == ("verification", "logs"):
            continue          # written by the runs themselves
        out[str(rel)] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    room = Path(sys.argv[1])
    a, b = files(ROOT), files(room)
    now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    print("### CLEAN-ROOM COMPARISON AGAINST THE WORKING TREE")
    print(f"### {now}")
    print(f"### working tree : {ROOT}")
    print(f"### clean room   : {room}")
    print("### independent extraction of the release archive, fresh virtual")
    print("### environment from requirements.lock, fresh clones of all three")
    print("### pinned sources. verification/logs/ is excluded: those logs are")
    print("### written by the runs themselves.")
    print()

    only_a = sorted(set(a) - set(b))
    only_b = sorted(set(b) - set(a))
    same = sorted(k for k in a if k in b and a[k] == b[k])
    diff = sorted(k for k in a if k in b and a[k] != b[k])
    print(f"identical            : {len(same)}")
    print(f"differing            : {len(diff)}")
    print(f"only in working tree : {len(only_a)}  {only_a}")
    print(f"only in clean room   : {len(only_b)}  {only_b}")
    print()

    print("### IDENTICAL (byte-for-byte across two independent runs)")
    for k in same:
        print(f"  {a[k][:16]}  {k}")
    print()

    unexplained_files = []
    print("### DIFFERING — each needs a stated, checked explanation")
    for k in diff:
        pa, pb = ROOT / k, room / k
        if k.endswith(".pdf"):
            ta = subprocess.run(["pdftotext", str(pa), "-"],
                                capture_output=True).stdout
            tb = subprocess.run(["pdftotext", str(pb), "-"],
                                capture_output=True).stdout
            strip = lambda t: re.sub(                       # noqa: E731
                rb"generated 20\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ", b"", t)
            ok = strip(ta) == strip(tb)
            print(f"  {k}: text layer identical once the generation timestamp "
                  f"is removed: {'YES' if ok else 'NO'}")
            if not ok:
                unexplained_files.append(k)
            continue
        la, lb = pa.read_bytes().splitlines(), pb.read_bytes().splitlines()
        if k == ".gitignore":
            extra = sorted({l.decode() for l in la + lb
                            if (l in la) != (l in lb)})
            print(f"  {k}: differs by {extra} — ignore rules added to the "
                  f"working tree after the clean-room archive was built. "
                  f"Carried into the delivered archive.")
            continue
        if len(la) != len(lb):
            short, long_ = (la, lb) if len(la) < len(lb) else (lb, la)
            who = "clean room" if len(lb) > len(la) else "working tree"
            prefix = short == long_[:len(short)]
            print(f"  {k}: {len(la)} vs {len(lb)} lines; the {who} holds "
                  f"{len(long_) - len(short)} more. Append-only, earlier lines "
                  f"unchanged: {'YES' if prefix else 'NO'}")
            if not prefix:
                unexplained_files.append(k)
            continue
        changed = [(i + 1, x, y) for i, (x, y) in enumerate(zip(la, lb))
                   if x != y]
        unexplained = [c for c in changed
                       if not TS.search(c[1]) and not TS.search(c[2])]
        print(f"  {k}: {len(changed)} line(s) differ, "
              f"{len(changed) - len(unexplained)} timestamp-only, "
              f"{len(unexplained)} unexplained")
        for i, x, y in unexplained[:4]:
            print(f"      line {i}:")
            print(f"        tree: {x[:120]!r}")
            print(f"        room: {y[:120]!r}")
        if unexplained:
            unexplained_files.append(k)
    print()

    print("### FIGURES (defect A1 regression check: byte-identical under the "
          "pinned dependencies)")
    for k in ("report/figures/fig01_field_timeline.png",
              "report/figures/fig02_catalog_growth.png"):
        if k in a and k in b:
            print(f"  {'IDENTICAL' if a[k] == b[k] else 'DIFFERS'}  {k}  "
                  f"{a[k][:16]}")
    print()

    print("### RELEASE-STATE EVIDENCE")
    doi_re = re.compile(r"10[.][0-9]{4,9}/")
    for base, name in ((ROOT, "working tree"), (room, "clean room  ")):
        cff = (base / "CITATION.cff").read_text()
        rd = (base / "README.md").read_text()
        rep = (base / "report" / "kev_schema_evolution.md").read_text()
        print(f"  {name}: date-released in CITATION.cff: "
              f"{'PRESENT' if 'date-released:' in cff else 'absent'}"
              f"; DOI-shaped strings in README + CITATION.cff + report: "
              f"{len(doi_re.findall(rd + cff + rep))}"
              f"; README status: "
              f"{'DRAFT' if 'STATUS: DRAFT' in rd else 'released'}")
    print()
    verdict = "NO UNEXPLAINED DIFFERENCES" if not unexplained_files else \
        f"UNEXPLAINED: {unexplained_files}"
    print(f"### VERDICT: {verdict}")
    print("### END COMPARISON")
    return 0 if not unexplained_files else 1


if __name__ == "__main__":
    raise SystemExit(main())
